[package]
name = "tui-flashcards"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
#clap = { version = "4.5.31", features = ["derive"] }
ratatui = "0.29.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"

